# Generated by Django 4.1.7 on 2023-06-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_stati_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stati',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статья'},
        ),
    ]
