# Generated by Django 4.1.7 on 2023-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_stati_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stati',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
