# Generated by Django 4.1.7 on 2023-06-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_stati_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stati',
            old_name='content',
            new_name='opisanie',
        ),
    ]
